-- ============================================================================
-- ARSIP HISTORIS — TIDAK DIPAKAI RUNTIME.
-- Skema PostgreSQL/Supabase lama sebelum migrasi ke SQLite (2026-09-29).
-- Skema aktif: src/database/schema.sql (SQLite). Lihat docs/MIGRATION_SUPABASE_TO_SQLITE.md.
-- ============================================================================
-- 001_initial_schema.sql
-- Bot Khutbah Jumat — skema awal (Supabase PostgreSQL)
--
-- Reproducible & idempoten: aman dijalankan berulang kali.
-- Jalankan lewat `npm run migrate -- --apply` (butuh DATABASE_URL) atau
-- `psql "$DATABASE_URL" -f supabase/migrations/001_initial_schema.sql`.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- articles
-- ---------------------------------------------------------------------------
create table if not exists public.articles (
  id             bigint generated by default as identity primary key,
  title          text not null,
  slug           text,
  url            text not null,
  author         text,
  published_at   timestamptz,
  language       text default 'id',
  description    text,
  snippet        text,
  category       text,
  content        text,
  khutbah_1      text,
  khutbah_2      text,
  image_url      text,
  source         text not null default 'NU Online',
  content_hash   text,
  status         text not null default 'active',
  last_synced_at timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint articles_status_check check (status in ('active', 'parse_failed', 'archived')),
  constraint articles_url_not_blank check (length(btrim(url)) > 0)
);

-- Kolom yang mungkin belum ada pada instalasi lama (idempoten).
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'articles' and column_name = 'image_url'
  ) then
    alter table public.articles add column image_url text;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'articles' and column_name = 'last_synced_at'
  ) then
    alter table public.articles add column last_synced_at timestamptz;
  end if;

  -- Kolom tsvector tergenerasi dengan pembobotan (judul > deskripsi/tag > isi).
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'articles' and column_name = 'search_vector'
  ) then
    alter table public.articles
      add column search_vector tsvector generated always as (
        setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(category, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(snippet, '')), 'C') ||
        setweight(to_tsvector('simple', coalesce(content, '')), 'C')
      ) stored;
  end if;
end $$;

-- UNIQUE url => mencegah duplikasi artikel oleh scraper.
create unique index if not exists articles_url_key on public.articles (url);
create index if not exists articles_published_at_idx on public.articles (published_at desc nulls last);
create index if not exists articles_status_idx on public.articles (status);
create index if not exists articles_content_hash_idx on public.articles (content_hash);
create index if not exists articles_search_vector_idx on public.articles using gin (search_vector);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
create table if not exists public.users (
  id             bigint generated by default as identity primary key,
  telegram_id    bigint not null,
  username       text,
  first_name     text,
  last_name      text,
  created_at     timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  constraint users_telegram_id_positive check (telegram_id > 0)
);
-- Telegram User ID harus UNIQUE.
create unique index if not exists users_telegram_id_key on public.users (telegram_id);
create index if not exists users_last_active_idx on public.users (last_active_at desc);

-- ---------------------------------------------------------------------------
-- favorites (anti-duplikat per user+artikel)
-- ---------------------------------------------------------------------------
create table if not exists public.favorites (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users (id) on delete cascade,
  article_id bigint not null references public.articles (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_article_key unique (user_id, article_id)
);
create index if not exists favorites_user_idx on public.favorites (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- history
-- ---------------------------------------------------------------------------
create table if not exists public.history (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users (id) on delete cascade,
  article_id bigint not null references public.articles (id) on delete cascade,
  opened_at  timestamptz not null default now()
);
create index if not exists history_user_idx on public.history (user_id, opened_at desc);

-- ---------------------------------------------------------------------------
-- search_logs (ringan, tanpa data sensitif yang tak perlu)
-- ---------------------------------------------------------------------------
create table if not exists public.search_logs (
  id           bigint generated by default as identity primary key,
  user_id      bigint references public.users (id) on delete set null,
  query        text not null,
  result_count integer not null default 0,
  created_at   timestamptz not null default now(),
  constraint search_logs_query_len check (char_length(query) <= 500),
  constraint search_logs_result_count_valid check (result_count >= 0)
);
create index if not exists search_logs_created_idx on public.search_logs (created_at desc);

-- ---------------------------------------------------------------------------
-- sync_logs
-- ---------------------------------------------------------------------------
create table if not exists public.sync_logs (
  id                bigint generated by default as identity primary key,
  started_at        timestamptz not null default now(),
  finished_at       timestamptz,
  articles_found    integer not null default 0,
  articles_inserted integer not null default 0,
  articles_updated  integer not null default 0,
  articles_failed   integer not null default 0,
  status            text not null default 'running',
  error_message     text,
  constraint sync_logs_status_check check (status in ('running', 'success', 'partial', 'failed')),
  constraint sync_logs_counts_valid check (
    articles_found >= 0 and articles_inserted >= 0 and
    articles_updated >= 0 and articles_failed >= 0
  )
);
create index if not exists sync_logs_started_idx on public.sync_logs (started_at desc);

-- ---------------------------------------------------------------------------
-- Trigger updated_at (articles)
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists articles_set_updated_at on public.articles;
create trigger articles_set_updated_at
  before update on public.articles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Fungsi pencarian (FTS) — mengembalikan { total, items } sebagai JSONB.
-- ---------------------------------------------------------------------------
create or replace function public.search_articles(
  p_query  text,
  p_limit  integer default 8,
  p_offset integer default 0
)
returns jsonb
language sql
stable
as $$
  with q as (
    select websearch_to_tsquery('simple', p_query) as query
  ),
  matched as (
    select a.*, ts_rank(a.search_vector, q.query) as rank
    from public.articles a, q
    where a.status = 'active' and a.search_vector @@ q.query
  ),
  total as (select count(*)::int as n from matched),
  page as (
    select * from matched
    order by rank desc, published_at desc nulls last
    limit p_limit offset p_offset
  )
  select jsonb_build_object(
    'total', (select n from total),
    'items', coalesce((select jsonb_agg(to_jsonb(p)) from page p), '[]'::jsonb)
  );
$$;

-- ---------------------------------------------------------------------------
-- Keamanan (least privilege)
--
-- RLS diaktifkan pada SEMUA tabel. Backend memakai SUPABASE_SECRET_KEY yang
-- melewati (bypass) RLS, sehingga TIDAK ada API publik yang dibuka.
-- Tidak ada policy untuk `anon`/`authenticated` => akses publik ditolak.
--
-- Jika kelak butuh akses baca publik terbatas, tambahkan policy eksplisit
-- (mis. hanya kolom metadata artikel aktif) — jangan menonaktifkan RLS.
-- ---------------------------------------------------------------------------
alter table public.articles    enable row level security;
alter table public.users       enable row level security;
alter table public.favorites   enable row level security;
alter table public.history     enable row level security;
alter table public.search_logs enable row level security;
alter table public.sync_logs   enable row level security;

-- Pastikan tidak ada policy publik yang tertinggal dari versi lama.
drop policy if exists articles_public_read on public.articles;

-- ---------------------------------------------------------------------------
-- Privilese Data API (least privilege)
--
-- Peran API di project ini TIDAK otomatis mendapat DML (hanya Dxtm), sehingga
-- backend perlu GRANT eksplisit. Backend memakai satu-satunya peran tepercaya:
-- `service_role` (dipakai oleh SUPABASE_SECRET_KEY, dan bypass RLS).
-- `anon`/`authenticated` sengaja TIDAK diberi privilese apa pun.
-- ---------------------------------------------------------------------------
grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
