-- ============================================================================
-- Bot Khutbah Jumat — Skema database (Supabase PostgreSQL)
-- Idempoten: aman dijalankan berulang kali.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- articles
-- ---------------------------------------------------------------------------
create table if not exists public.articles (
  id            bigint generated by default as identity primary key,
  title         text not null,
  slug          text,
  url           text not null,
  author        text,
  published_at  timestamptz,
  language      text default 'id',
  description   text,
  category      text,
  content       text,
  khutbah_1     text,
  khutbah_2     text,
  source        text default 'NU Online',
  content_hash  text,
  status        text not null default 'active',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint articles_status_check check (status in ('active', 'parse_failed', 'archived'))
);

-- Kolom tsvector tergenerasi dengan pembobotan (judul > deskripsi/tag > isi).
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'articles' and column_name = 'search_vector'
  ) then
    alter table public.articles
      add column search_vector tsvector generated always as (
        setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(category, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(content, '')), 'C')
      ) stored;
  end if;
end $$;

create unique index if not exists articles_url_key on public.articles (url);
create index if not exists articles_published_at_idx on public.articles (published_at desc nulls last);
create index if not exists articles_status_idx on public.articles (status);
create index if not exists articles_content_hash_idx on public.articles (content_hash);
create index if not exists articles_search_vector_idx on public.articles using gin (search_vector);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
create table if not exists public.users (
  id             bigint generated by default as identity primary key,
  telegram_id    bigint not null,
  username       text,
  first_name     text,
  last_name      text,
  created_at     timestamptz not null default now(),
  last_active_at timestamptz not null default now()
);
create unique index if not exists users_telegram_id_key on public.users (telegram_id);

-- ---------------------------------------------------------------------------
-- favorites
-- ---------------------------------------------------------------------------
create table if not exists public.favorites (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users (id) on delete cascade,
  article_id bigint not null references public.articles (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_article_key unique (user_id, article_id)
);
create index if not exists favorites_user_idx on public.favorites (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- history
-- ---------------------------------------------------------------------------
create table if not exists public.history (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users (id) on delete cascade,
  article_id bigint not null references public.articles (id) on delete cascade,
  opened_at  timestamptz not null default now()
);
create index if not exists history_user_idx on public.history (user_id, opened_at desc);

-- ---------------------------------------------------------------------------
-- search_logs
-- ---------------------------------------------------------------------------
create table if not exists public.search_logs (
  id           bigint generated by default as identity primary key,
  user_id      bigint references public.users (id) on delete set null,
  query        text not null,
  result_count integer not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists search_logs_created_idx on public.search_logs (created_at desc);

-- ---------------------------------------------------------------------------
-- sync_logs
-- ---------------------------------------------------------------------------
create table if not exists public.sync_logs (
  id                 bigint generated by default as identity primary key,
  started_at         timestamptz not null default now(),
  finished_at        timestamptz,
  articles_found     integer not null default 0,
  articles_inserted  integer not null default 0,
  articles_updated   integer not null default 0,
  articles_failed    integer not null default 0,
  status             text not null default 'running',
  error_message      text,
  constraint sync_logs_status_check check (status in ('running', 'success', 'partial', 'failed'))
);
create index if not exists sync_logs_started_idx on public.sync_logs (started_at desc);

-- ---------------------------------------------------------------------------
-- Trigger updated_at
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists articles_set_updated_at on public.articles;
create trigger articles_set_updated_at
  before update on public.articles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Fungsi pencarian (FTS + fallback)
-- Mengembalikan { total, items } sebagai JSONB.
-- ---------------------------------------------------------------------------
create or replace function public.search_articles(
  p_query  text,
  p_limit  integer default 8,
  p_offset integer default 0
)
returns jsonb
language sql
stable
as $$
  with q as (
    select websearch_to_tsquery('simple', p_query) as query
  ),
  matched as (
    select a.*, ts_rank(a.search_vector, q.query) as rank
    from public.articles a, q
    where a.status = 'active' and a.search_vector @@ q.query
  ),
  total as (select count(*)::int as n from matched),
  page as (
    select * from matched
    order by rank desc, published_at desc nulls last
    limit p_limit offset p_offset
  )
  select jsonb_build_object(
    'total', (select n from total),
    'items', coalesce((select jsonb_agg(to_jsonb(p)) from page p), '[]'::jsonb)
  );
$$;

-- ---------------------------------------------------------------------------
-- Hak akses: RLS aktif. Server tepercaya memakai service_role (bypass RLS).
-- Bila memakai anon key, tambahkan policy sesuai kebutuhan (lihat komentar).
-- ---------------------------------------------------------------------------
alter table public.articles    enable row level security;
alter table public.users       enable row level security;
alter table public.favorites   enable row level security;
alter table public.history     enable row level security;
alter table public.search_logs enable row level security;
alter table public.sync_logs   enable row level security;

-- Indeks artikel publik boleh dibaca anon (metadata). Data pengguna TIDAK.
drop policy if exists articles_public_read on public.articles;
create policy articles_public_read on public.articles
  for select to anon, authenticated
  using (status = 'active');

-- CATATAN KEAMANAN:
-- * users/favorites/history/search_logs/sync_logs sengaja TANPA policy publik.
--   Hanya service_role (server Termux) yang boleh mengaksesnya.
-- * Jangan pernah memakai service_role key di klien publik.
